
server:
  default_path: "../Cloud/running/static"
  version: "paper-1.21.1-133.jar"
  check_delay: 10            # Zeit in Sekunden nach Start, um den Online-Status zu prüfen

cloud:
  autoregister: true         # Server aus dem Standardpfad automatisch registrieren
  debug_mode: false          # Entwicklernachrichten aktivieren
  host: "localhost"          # Adresse von EchoCloud
  port: 9989                 # Port von EchoCloud

network:
  use_https: true            # HTTPS für Server-Kommunikation aktivieren
  auto_cert: true            # HTTPS-Zertifikat automatisch generieren
  auto_api: false            # API Automatisch beim start von EchoCloud Starten
  cert_duration_days: 365    # Gültigkeitsdauer des Zertifikats
  auth_config_path: "./config/auth_tokens.yaml"    # Pfad von auth_tokens.yaml
  cert_file_path: "./config/cert.pem"              # Pfad zum Zertifikat
  key_file_path: "./config/key.pem"                # Pfad zum Schlüssel des Zertifikats

storage:
  storage_type: "h2"         # Optionen: "mysql", "mariadb", "postgresql", "h2"
  host: "localhost"          # Datenbankhost (nur bei MySQL/MariaDB/PostgreSQL)
  port: 3306                 # Standardports: MySQL/MariaDB: 3306, PostgreSQL: 5432
  username: "root"           # Datenbankbenutzer
  password: "passwort"       # Datenbankpasswort
  database: "EchoCloud"      # Datenbankname
  table_name: "json_storage" # Tabelle für EchoCloud-Daten
  h2_file_path: "data/"      # Pfad zur H2-Datei