
server:
  default_path: "../Cloud/running/static"
  heartbeat_delay: 10        # Intervall des Heartbeats von jedem Server. Dies updatet alle LaufzeitInfos von jedem Server.

cloud:
  autoregister: true         # Server aus dem Standardpfad automatisch registrieren
  debug_mode: false          # Entwicklernachrichten aktivieren
  host: "127.0.0.1"          # Adresse von EchoCloud WebSocket / Redis Server. Diese Adresse muss auch Bei allen Servern Angegeben werden!
  port: 6379                 # Port von EchoCloud WebSocket / Redis Server.

network:
  communication_type: "redis"          # Kommunikationsart "Redis" oder "Websocket"
  redis_channel: "echocloud:all"       # Redis Channel Name. Wird nur benötigt wenn communication_type: "Redis"
  redis_user: "default"                # Redis Benutzer. Falls du keinen Angelegt hast lasse "default"
  redis_password: "2487892374983"      # Redis Passwort falls gesetzt. Du kannst dein Redis Password unter .. ändern. Suche nach requirepass [passwort]
  use_https: true                      # HTTPS für Server-Kommunikation aktivieren
  auto_cert: true                      # HTTPS-Zertifikat automatisch generieren
  auto_api: true                       # API Automatisch beim start von EchoCloud Starten
  cert_duration_days: 365              # Gültigkeitsdauer des Zertifikats
  auth_config_path: "./config/auth_tokens.yaml"    # Pfad von auth_tokens.yaml
  cert_file_path: "./config/cert.pem"              # Pfad zum Zertifikat
  key_file_path: "./config/key.pem"                # Pfad zum Schlüssel des Zertifikats

storage:
  storage_type: "h2"         # Optionen: "mysql", "mariadb", "postgresql", "h2"
  host: "localhost"          # Datenbankhost (nur bei MySQL/MariaDB/PostgreSQL)
  port: 3306                 # Standardports: MySQL/MariaDB: 3306, PostgreSQL: 5432
  username: "root"           # Datenbankbenutzer
  password: "passwort"       # Datenbankpasswort
  database: "EchoCloud"      # Datenbankname
  table_name: "json_storage" # Tabelle für EchoCloud-Daten
  h2_file_path: "data/"      # Pfad zur H2-Datei